
import django_filters
from .models import Dentalpro

COUNTY_CHOICES = (
    ('ALAMANCE', 'ALAMANCE'),
    ('ALEXANDER', 'ALEXANDER'),
    ('ALLEGHANY', 'ALLEGHANY'),
    ('ANSON', 'ANSON'),
    ('ASHE', 'ASHE'),
    ('AVERY', 'AVERY'),
    ('BEAUFORT', 'BEAUFORT'),
    ('BERTIE', 'BERTIE'),
    ('BLADEN', 'BLADEN'),
    ('BRUNSWICK', 'BRUNSWICK'),
    ('BUNCOMBE', 'BUNCOMBE'),
    ('BURKE', 'BURKE'),
    ('CABARRUS', 'CABARRUS'),
    ('CALDWELL', 'CALDWELL'),
    ('CAMDEN', 'CAMDEN'),
    ('CARTERET', 'CARTERET'),
    ('CASWELL', 'CASWELL'),
    ('CATAWBA', 'CATAWBA'),
    ('CHATHAM', 'CHATHAM'),
    ('CHEROKEE', 'CHEROKEE'),
    ('CHOWAN', 'CHOWAN'),
    ('CLAY', 'CLAY'),
    ('CLEVELAND', 'CLEVELAND'),
    ('COLUMBUS', 'COLUMBUS'),
    ('COUNTY', 'COUNTY'),
    ('CRAVEN', 'CRAVEN'),
    ('CUMBERLAND', 'CUMBERLAND'),
    ('CURRITUCK', 'CURRITUCK'),
    ('DARE', 'DARE'),
    ('DAVIDSON', 'DAVIDSON'),
    ('DAVIE', 'DAVIE'),
    ('DUPLIN', 'DUPLIN'),
    ('DURHAM', 'DURHAM'),
    ('EDGECOMBE', 'EDGECOMBE'),
    ('FORSYTH', 'FORSYTH'),
    ('FRANKLIN', 'FRANKLIN'),
    ('GASTON', 'GASTON'),
    ('GATES', 'GATES'),
    ('GRAHAM', 'GRAHAM'),
    ('GRANVILLE', 'GRANVILLE'),
    ('GREENE', 'GREENE'),
    ('GUILFORD', 'GUILFORD'),
    ('HALIFAX', 'HALIFAX'),
    ('HARNETT', 'HARNETT'),
    ('HAYWOOD', 'HAYWOOD'),
    ('HENDERSON', 'HENDERSON'),
    ('HERTFORD', 'HERTFORD'),
    ('HOKE', 'HOKE'),
    ('HYDE', 'HYDE'),
    ('IREDELL', 'IREDELL'),
    ('JACKSON', 'JACKSON'),
    ('JOHNSTON', 'JOHNSTON'),
    ('JONES', 'JONES'),
    ('LEE', 'LEE'),
    ('LENOIR', 'LENOIR'),
    ('LINCOLN', 'LINCOLN'),
    ('MACON', 'MACON'),
    ('MADISON', 'MADISON'),
    ('MARTIN', 'MARTIN'),
    ('MCDOWELL', 'MCDOWELL'),
    ('MECKLENBURG', 'MECKLENBURG'),
    ('MITCHELL', 'MITCHELL'),
    ('MONTGOMERY', 'MONTGOMERY'),
    ('MOORE', 'MOORE'),
    ('NASH', 'NASH'),
    ('NEW HANOVER', 'NEW HANOVER'),
    ('NORTHAMPTON', 'NORTHAMPTON'),
    ('ONSLOW', 'ONSLOW'),
    ('ORANGE', 'ORANGE'),
    ('PAMLICO', 'PAMLICO'),
    ('PASQUOTANK', 'PASQUOTANK'),
    ('PENDER', 'PENDER'),
    ('PERQUIMANS', 'PERQUIMANS'),
    ('PERSON', 'PERSON'),
    ('PITT', 'PITT'),
    ('POLK', 'POLK'),
    ('RANDOLPH', 'RANDOLPH'),
    ('RICHMOND', 'RICHMOND'),
    ('ROBESON', 'ROBESON'),
    ('ROCKINGHAM', 'ROCKINGHAM'),
    ('ROWAN', 'ROWAN'),
    ('RUTHERFORD', 'RUTHERFORD'),
    ('SAMPSON', 'SAMPSON'),
    ('SCOTLAND', 'SCOTLAND'),
    ('STANLY', 'STANLY'),
    ('STOKES', 'STOKES'),
    ('SURRY', 'SURRY'),
    ('SWAIN', 'SWAIN'),
    ('TRANSYLVANIA', 'TRANSYLVANIA'),
    ('UNION', 'UNION'),
    ('VANCE', 'VANCE'),
    ('WAKE', 'WAKE'),
    ('WARREN', 'WARREN'),
    ('WASHINGTON', 'WASHINGTON'),
    ('WATAUGA', 'WATAUGA'),
    ('WAYNE', 'WAYNE'),
    ('WILKES', 'WILKES'),
    ('WILSON', 'WILSON'),
    ('YADKIN', 'YADKIN'),
    ('YANCEY', 'YANCEY'),
)
SPECIALTY_CHOICES =(
    ('Dental Public Health', 'Dental Public Health'),
    ('Endodontics', 'Endodontics'),
    ('General Practice', 'General Practice'),
    ('Oral Pathology', 'Oral Pathology'),
    ('Oral Surgery', 'Oral Surgery'),
    ('Oral/Maxil Surgery', 'Oral/Maxil Surgery'),
    ('Oral/Maxil. Surgery', 'Oral/Maxil. Surgery'),
    ('Oral/Maxil.Radiology', 'Oral/Maxil.Radiology'),
    ('Orthodontics', 'Orthodontics'),
    ('Pediatric Dentistry', 'Pediatric Dentistry'),
    ('Periodontics', 'Periodontics'),
    ('Prosthodontics', 'Prosthodontics'),
)
ACTIVE_CHOICES =(
    ('Y', 'Y'),
    ('N', 'N'),
)
class DentalproFilter(django_filters.FilterSet):
    lastname = django_filters.CharFilter()
    firstname = django_filters.CharFilter()
    county = django_filters.ChoiceFilter(choices=COUNTY_CHOICES)
    active = django_filters.ChoiceFilter(choices=ACTIVE_CHOICES)
    specialty = django_filters.ChoiceFilter(choices=SPECIALTY_CHOICES)
    licenseid = django_filters.CharFilter()


    class Meta:
        model = Dentalpro
        fields = ('lastname', 'firstname',
                  'county', 'active', 'specialty', 'licenseid')

